### ISSUE TITLE
is gwas really working?

### ISSUE THREAD

**Issue by BjoernUsadel** [usadellab/untwistApp#10]
even simple normal GWAS runs forever. Web developer console is full of problems However connection to the server seems very slow

**Comment by ataulhaleem** [comment]
possible reasons could be that I was running the default backend flask server, which has limited capabilities and is only suitable for development purposes, however I have now changed it to the WSGI a production server for flask and enabled it to use 20 threads from my machine, hopefully it will solve the connection to the server issue, please let me know if it does not. 

normal GWAS should not take more then 3-5 minutes. If it does, most probably your token is expired. please refresh your page and it should work fine, but I will update the app to update the token automatically. But thanks for the feedback.

Also I will advise using browser in the incognito mode for best performance evaluation.

![image](https://github.com/usadellab/untwistApp/assets/29739514/864bf43a-ee8f-43fe-8fd7-fdcd01dca34f)

**Comment by BjoernUsadel** [comment]
works now
