### ISSUE TITLE
wired crashes

### ISSUE THREAD

**Issue by BjoernUsadel** [usadellab/untwistApp#12]
after some time this comes up
![grafik](https://github.com/usadellab/untwistApp/assets/36935129/5e76801e-3853-4ff8-8e00-097732df465d)

**Comment by ataulhaleem** [comment]
this is syntax error, unfortunately you were using the app at the same time I was making changes in this code. 
the code is not the same any more as it looks in the screenshot. The component work fine, apologies for any inconvenience but thank you for the feedback. If you still get this error please reopen the issue.. 
![image](https://github.com/usadellab/untwistApp/assets/29739514/24866297-ff80-483d-9e93-882aadabaa98)
