### ISSUE TITLE
NA genotypes do not exist in readme this must be something

### ISSUE THREAD

**Issue by BjoernUsadel** [usadellab/untwistApp#14]

**Comment by ataulhaleem** [comment]
Apologies for the delayed response. Yes its not properly described. NA means the samples where the meta data on the name or the cultivar or its tissue is not available, and vice versa is missing. 

![image](https://github.com/usadellab/untwistApp/assets/29739514/8696917f-cb57-4462-a86a-513a20b80ba5)

This information is redirected to the online documentation now at [https://ataulhaleem.github.io/camelina-hub-documentation/modules/jbrowse](https://ataulhaleem.github.io/camelina-hub-documentation/modules/jbrowse)
