### ISSUE TITLE
Dark Mode is not working properly

### ISSUE THREAD

**Issue by AngelaKranz** [usadellab/untwistApp#22]
On the main page, when I activate Dark Mode, most of the text below the image disappears:

![image](https://github.com/user-attachments/assets/4b2fcba2-a513-4c98-9958-54f002c986b0)

![image](https://github.com/user-attachments/assets/8bcc7752-72f0-4ee3-ac7f-201a35f83c95)

**Comment by ataulhaleem** [comment]
fixed thank you
