### ISSUE TITLE
GWAS selection still broken

### ISSUE THREAD

**Issue by BjoernUsadel** [usadellab/untwistApp#23]
plot shows many more dots than annotaton
plot
![grafik](https://github.com/user-attachments/assets/abfbd298-7aa6-4909-b299-7aec0fae9179)
annotations
![grafik](https://github.com/user-attachments/assets/dfcb7079-3188-4ba2-971a-a906ef3d56e3)

**Comment by ataulhaleem** [comment]
fixed indentation error during deployment
