### ISSUE TITLE
User interface

### ISSUE THREAD

**Issue by BjoernUsadel** [usadellab/untwistApp#25]
The studies make it very hard to use. At least put camelina in the study names

**Comment by ataulhaleem** [comment]
The study selection drop down has been replaced with a power full data search engine, which enable search data based on keywords

![image](https://github.com/user-attachments/assets/27ac3c75-e8a9-4f99-ad5e-7eeef860a28f)

a click is enough to load the corresponding datasets.
there are some hover over options for interactivity as well.

**Comment by ataulhaleem** [comment]
finally settled for this version. it allow AND OR queries. 

![image](https://github.com/user-attachments/assets/dbbf964d-1f0b-4db9-93b1-d179e61b9da9)

**Comment by BjoernUsadel** [comment]
keep your user base in mind | is not understandable use OR and AND (+ is good but I don't know a term that is clear)

**Comment by ataulhaleem** [comment]
indeed this should be addressed, thank you. Now the search looks like this 

![image](https://github.com/user-attachments/assets/e464060f-5251-4686-93ee-f516a5c6c0d5)

and it is possible to combine symbols and letter operators e.g 

stress and seed or multiple
stress + seed or multiple
stress + seed | multiple
stress | seed | multiple
stress | seed and multiple

![image](https://github.com/user-attachments/assets/a386cf71-bef3-479a-85af-2366de74e051)
