### ISSUE TITLE
user friendliness

### ISSUE THREAD

**Issue by BjoernUsadel** [usadellab/untwistApp#3]
currently all traits are dumped and listed this is not sustainable also there is no description of traits or where they are coming from

**Comment by ataulhaleem** [comment]
![image](https://github.com/usadellab/untwistApp/assets/29739514/938f640c-a37d-4dec-b80f-1ceb0ff5d915)

The phenotype descriptors, given the information I was able to collect are curated in the following way that each entry in the drop down menu describes the 

 **'Phenotype' _ 'measurement unit' _ 'Stress treatment(if any)' _ 'Growth stage/collection date(if available)' _ 'provider(if available)'**

This allows to compare between trait data as well conditions. If there are other suggestions, please let me know.

**Comment by BjoernUsadel** [comment]
Sorry the logic is there but
look at the following 
![grafik](https://github.com/usadellab/untwistApp/assets/36935129/e30391e6-f688-4e8b-b86d-3df95f77a1f6)
this list will and can only grow and you can't jsut make this list arbirtarly long
Get maybe Marius and others to look at it you need to sturcture your data somewhat I am not sure 
e.g. group the metabolites and phenotypic data so it opens as a seperate explodable undermenu

**Comment by ataulhaleem** [comment]
the data is now devided into three categories as you see below 

![image](https://github.com/usadellab/untwistApp/assets/29739514/bb6f4f38-93ac-4982-a6ec-44273f4550bc)

user can make one, more than one or all selections.
  - in case of a single selection only the data collected under that category will be shown in the drop down menu
  - if user selects more than one categories, those datasets will be aggregated and he can work with both datasets simultaneously
  - if All is selected all data sets will be available for plotting

![image](https://github.com/usadellab/untwistApp/assets/29739514/ed72f7da-2b82-4826-9460-426e27aeb63c)

**Comment by BjoernUsadel** [comment]
much better but if I want to show one versus the other I have the same problem
I was thinking more something like this
https://www.jqueryscript.net/form/Select-Boxes-Replacement-Plugin-Select2.html
Or better yet that you can open up different sections
Remeber we will have much much more data sets
and also talk to Marius

**Comment by ataulhaleem** [comment]
Thank you for the example, I have now adapted accordingly.

![Screenshot from 2023-10-10 15-46-35](https://github.com/usadellab/untwistApp/assets/29739514/35bc7f57-f91f-4046-bd05-bffe948f7cdd)

Also for the popup

![image](https://github.com/usadellab/untwistApp/assets/29739514/f4119206-8ce3-4a39-b438-4e9c42ebce71)


I still see an opportunity to summarize the data further, it will reduce the data points but may be easier to understand. e.g 
the corresponding data can be aggregated to take averages. 

![image](https://github.com/usadellab/untwistApp/assets/29739514/9e3eb922-8779-4792-97bf-b3ae79d9d9a4)

@Marius also please let me know what do you think or if you have any other suggestion please feel free to comment.

**Comment by BjoernUsadel** [comment]
the @s are gone it seems but this is still not user friendly and unordered and will not scale to more data

**Comment by BjoernUsadel** [comment]
see oabove
