### ISSUE TITLE
Copyright years are wrong

### ISSUE THREAD

**Issue by AngelaKranz** [usadellab/untwistApp#30]
Not sure why it says 2014-2023:

![image](https://github.com/user-attachments/assets/228c8348-03f7-4fb4-84eb-acb52ce3e058)

**Comment by ataulhaleem** [comment]
![image](https://github.com/user-attachments/assets/cb9ee266-1d62-48e6-9197-02f9f54bcad1)

i also moved to 2024 since this is from last year.
