### ISSUE TITLE
Impressum is missing

### ISSUE THREAD

**Issue by AngelaKranz** [usadellab/untwistApp#38]

**Comment by AngelaKranz** [comment]
This should not be hidden in the FAQs. Also, this is completely wrong:

![image](https://github.com/user-attachments/assets/fa5a4c37-4cb8-4f45-b4f4-0572ae06d6f1)

**Comment by ataulhaleem** [comment]
if you mean the names of people they are updated, but please have a look again, if the updated names are correct. Again this info is based on plabipd, any further changes if need please feel free to reopen the issue.
