### ISSUE TITLE
Download - You should explain RO-Crate/ARC

### ISSUE THREAD

**Issue by AngelaKranz** [usadellab/untwistApp#40]
You should definitely provide an explanation for this. Additionally, if ARCs are mentioned, DataPLANT must be credited.

**Comment by ataulhaleem** [comment]
again... its not and arc but research object (RO-crate), It could look similar to arc as it is based on ISA standards. In this app we use only MIAPPE attributes, so its not even full ARC-RO-create but precisely MIAPPE compliant ARC-RO-crate.

**Comment by AngelaKranz** [comment]
Again: Then do not mention that it is based on Annotated Research Context (ARC). That is completely wrong.

![image](https://github.com/user-attachments/assets/dd113ee2-1760-4c1e-b349-d5493807cdfa)

For info:
@BjoernUsadel
