### ISSUE TITLE
plot legends manuals

### ISSUE THREAD

**Issue by BjoernUsadel** [usadellab/untwistApp#5]
one can chnage x and y axis labels, this is a minor use case but it is not bad... But it should be autopopulated and once I replot different things rechange I think

**Comment by ataulhaleem** [comment]
Where possible e.g scatter plot, linReg plot x and y axis labels are automatically assigned  (though it is still possible to edit them).

For histogram only x variable is automatically assigned, as it is understood that its the count of individuals, different people call it Counts or Frequency so i left it open to edit.  

For raincloud, violin and box plots I can add the x or y tick labels but its already in the legend, please let me know here if we should add the tick labels as well.

I want to keep the legend as it lets one to reshape the plot e.g if one has selected to plot three box or violin or line plots together on one plot,  one can simply click on the legend to deselect or re-select the variable and the plot will be updated automatically. 


![image](https://github.com/usadellab/untwistApp/assets/29739514/7e1ddb98-2ddc-46c9-8f81-c452976ea432)


deselect on distribution from legend 

![image](https://github.com/usadellab/untwistApp/assets/29739514/cc481b51-ad3a-4274-a34e-07432b0c6ded)

but please let me know on this if its useful.
